version: '3.9'

services:
  nginx-proxy:
    build: .
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8008:8008"
      - "8009:8009"
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs/sites-enabled:/etc/nginx/conf.d:ro
    networks:
      - redis_network

networks:
  redis_network:
    external: true