version: '3.9'

services:
  redis:
    build: .
    container_name: redis_service
    restart: always
    ports:
      - "6379:6379"
    networks:
      - redis_network
    volumes:
      - ../../volumes/redis_data:/data
      - ./configs/redis.conf:/usr/local/etc/redis/redis.conf:ro

volumes:
  redis_data:
    driver: local

networks:
  redis_network:
    external: true
